#include <engine/platform/input_system.h>
#include <span>

constexpr engine::EKeyCode allKeyCodesCArray[]{
    engine::EKeyCode::Unknown,
    engine::EKeyCode::Space,
    engine::EKeyCode::Apostrophe,
    engine::EKeyCode::Comma,
    engine::EKeyCode::Minus,
    engine::EKeyCode::Period,
    engine::EKeyCode::Slash,
    engine::EKeyCode::Number0,
    engine::EKeyCode::Number1,
    engine::EKeyCode::Number2,
    engine::EKeyCode::Number3,
    engine::EKeyCode::Number4,
    engine::EKeyCode::Number5,
    engine::EKeyCode::Number6,
    engine::EKeyCode::Number7,
    engine::EKeyCode::Number8,
    engine::EKeyCode::Number9,
    engine::EKeyCode::Semicolon,
    engine::EKeyCode::Equal,
    engine::EKeyCode::A,
    engine::EKeyCode::B,
    engine::EKeyCode::C,
    engine::EKeyCode::D,
    engine::EKeyCode::E,
    engine::EKeyCode::F,
    engine::EKeyCode::G,
    engine::EKeyCode::H,
    engine::EKeyCode::I,
    engine::EKeyCode::J,
    engine::EKeyCode::K,
    engine::EKeyCode::L,
    engine::EKeyCode::M,
    engine::EKeyCode::N,
    engine::EKeyCode::O,
    engine::EKeyCode::P,
    engine::EKeyCode::Q,
    engine::EKeyCode::R,
    engine::EKeyCode::S,
    engine::EKeyCode::T,
    engine::EKeyCode::U,
    engine::EKeyCode::V,
    engine::EKeyCode::W,
    engine::EKeyCode::X,
    engine::EKeyCode::Y,
    engine::EKeyCode::Z,
    engine::EKeyCode::LeftBracket,
    engine::EKeyCode::Backslash,
    engine::EKeyCode::RightBracket,
    engine::EKeyCode::GraveAccent,
    engine::EKeyCode::World1,
    engine::EKeyCode::World2,
    engine::EKeyCode::Escape,
    engine::EKeyCode::Enter,
    engine::EKeyCode::Tab,
    engine::EKeyCode::Backspace,
    engine::EKeyCode::Insert,
    engine::EKeyCode::Delete,
    engine::EKeyCode::Right,
    engine::EKeyCode::Left,
    engine::EKeyCode::Down,
    engine::EKeyCode::Up,
    engine::EKeyCode::PageUp,
    engine::EKeyCode::PageDown,
    engine::EKeyCode::Home,
    engine::EKeyCode::End,
    engine::EKeyCode::CapsLock,
    engine::EKeyCode::ScrollLock,
    engine::EKeyCode::NumLock,
    engine::EKeyCode::PrintScreen,
    engine::EKeyCode::Pause,
    engine::EKeyCode::F1,
    engine::EKeyCode::F2,
    engine::EKeyCode::F3,
    engine::EKeyCode::F4,
    engine::EKeyCode::F5,
    engine::EKeyCode::F6,
    engine::EKeyCode::F7,
    engine::EKeyCode::F8,
    engine::EKeyCode::F9,
    engine::EKeyCode::F10,
    engine::EKeyCode::F11,
    engine::EKeyCode::F12,
    engine::EKeyCode::F13,
    engine::EKeyCode::F14,
    engine::EKeyCode::F15,
    engine::EKeyCode::F16,
    engine::EKeyCode::F17,
    engine::EKeyCode::F18,
    engine::EKeyCode::F19,
    engine::EKeyCode::F20,
    engine::EKeyCode::F21,
    engine::EKeyCode::F22,
    engine::EKeyCode::F23,
    engine::EKeyCode::F24,
    engine::EKeyCode::F25,
    engine::EKeyCode::Keypad0,
    engine::EKeyCode::Keypad1,
    engine::EKeyCode::Keypad2,
    engine::EKeyCode::Keypad3,
    engine::EKeyCode::Keypad4,
    engine::EKeyCode::Keypad5,
    engine::EKeyCode::Keypad6,
    engine::EKeyCode::Keypad7,
    engine::EKeyCode::Keypad8,
    engine::EKeyCode::Keypad9,
    engine::EKeyCode::KeypadDecimal,
    engine::EKeyCode::KeypadDivide,
    engine::EKeyCode::KeypadMultiply,
    engine::EKeyCode::KeypadSubtract,
    engine::EKeyCode::KeypadAdd,
    engine::EKeyCode::KeypadEnter,
    engine::EKeyCode::KeypadEqual,
    engine::EKeyCode::LeftShift,
    engine::EKeyCode::LeftControl,
    engine::EKeyCode::LeftAlt,
    engine::EKeyCode::LeftSuper,
    engine::EKeyCode::RightShift,
    engine::EKeyCode::RightControl,
    engine::EKeyCode::RightAlt,
    engine::EKeyCode::RightSuper,
    engine::EKeyCode::Menu,
    engine::EKeyCode::Mouse0,
    engine::EKeyCode::Mouse1,
    engine::EKeyCode::Mouse2,
    engine::EKeyCode::Mouse3,
    engine::EKeyCode::Mouse4,
    engine::EKeyCode::Mouse5,
    engine::EKeyCode::Mouse6,
    engine::EKeyCode::Mouse7,
};
constexpr std::span<const engine::EKeyCode> allKeyCodes = allKeyCodesCArray;
static_assert((int)allKeyCodes.back() == ((int)engine::EKeyCode::Count - 1), "Wrong keycodes count");

engine::InputSystem::InputSystem() {
    for (auto &key : allKeyCodes) {
        m_keyStates[key] = {};
    }
}
engine::InputSystem &engine::InputSystem::instance() {
    static InputSystem s_system{};
    return s_system;
}
void engine::InputSystem::reset() {
    for (auto &pair : m_keyStates) {
        pair.second = static_cast<KeyState>(pair.second & ~KS_HAS_INPUT_IN_THIS_FRAME);
    }
    m_mouseDelta.x = 0;
    m_mouseDelta.y = 0;
    m_scrollDelta.x = 0;
    m_scrollDelta.y = 0;
}
